---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hpxbxowy/public_html/
    - /bin/cp -R build/web/index.html $DEPLOYPATH
    - /bin/cp -R build/web/main.dart.js $DEPLOYPATH
    - /bin/cp -R build/web/assets $DEPLOYPATH
    - /bin/cp -R build/web/favicon.png $DEPLOYPATH
    - /bin/cp -R build/web/manifest.json $DEPLOYPATH
    - /bin/cp -R build/web/icons $DEPLOYPATH
    - /bin/cp -R build/web/version.json $DEPLOYPATH
    - /bin/cp -R build/web/flutter_service_worker.js $DEPLOYPATH
    - /bin/cp -R build/web/canvaskit $DEPLOYPATH
    - /bin/cp -R build/web/flutter.js $DEPLOYPATH
    - /bin/cp -R build/web/flutter_bootstrap.js $DEPLOYPATH
